# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonTypes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43ommonTypes.proto\x12\x04spex\"\x1f\n\x0eOptionalDouble\x12\r\n\x05value\x18\x01 \x01(\x01\"(\n\tNamesList\x12\x0c\n\x04left\x18\x01 \x01(\r\x12\r\n\x05names\x18\x02 \x03(\t\"@\n\x0cResourceItem\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.spex.ResourceType\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\".\n\tResources\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.spex.ResourceItem\"G\n\x08Property\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x1e\n\x06nested\x18\x03 \x03(\x0b\x32\x0e.spex.Property\"c\n\tBlueprint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\nproperties\x18\x02 \x03(\x0b\x32\x0e.spex.Property\x12$\n\x08\x65xpenses\x18\x03 \x03(\x0b\x32\x12.spex.ResourceItem\"8\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\n\n\x02vx\x18\x04 \x01(\x01\x12\n\n\x02vy\x18\x05 \x01(\x01\"|\n\x0ePhysicalObject\x12%\n\x0bobject_type\x18\x01 \x01(\x0e\x32\x10.spex.ObjectType\x12\n\n\x02id\x18\x02 \x01(\r\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\n\n\x02vx\x18\x05 \x01(\x02\x12\n\n\x02vy\x18\x06 \x01(\x02\x12\t\n\x01r\x18\x07 \x01(\x02\"I\n\x13PhysicalObjectsList\x12$\n\x06object\x18\x01 \x03(\x0b\x32\x14.spex.PhysicalObject\x12\x0c\n\x04left\x18\x02 \x01(\r*\x8b\x01\n\x0cResourceType\x12\x14\n\x10RESOURCE_UNKNOWN\x10\x00\x12\x13\n\x0fRESOURCE_METALS\x10\x01\x12\x16\n\x12RESOURCE_SILICATES\x10\x02\x12\x10\n\x0cRESOURCE_ICE\x10\x03\x12\x12\n\x0eRESOURCE_STONE\x10\x04\x12\x12\n\x0eRESOURCE_LABOR\x10\x65*F\n\nObjectType\x12\x12\n\x0eOBJECT_UNKNOWN\x10\x00\x12\x13\n\x0fOBJECT_ASTEROID\x10\x01\x12\x0f\n\x0bOBJECT_SHIP\x10\x02\x42\x03\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommonTypes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _RESOURCETYPE._serialized_start=650
  _RESOURCETYPE._serialized_end=789
  _OBJECTTYPE._serialized_start=791
  _OBJECTTYPE._serialized_end=861
  _OPTIONALDOUBLE._serialized_start=27
  _OPTIONALDOUBLE._serialized_end=58
  _NAMESLIST._serialized_start=60
  _NAMESLIST._serialized_end=100
  _RESOURCEITEM._serialized_start=102
  _RESOURCEITEM._serialized_end=166
  _RESOURCES._serialized_start=168
  _RESOURCES._serialized_end=214
  _PROPERTY._serialized_start=216
  _PROPERTY._serialized_end=287
  _BLUEPRINT._serialized_start=289
  _BLUEPRINT._serialized_end=388
  _POSITION._serialized_start=390
  _POSITION._serialized_end=446
  _PHYSICALOBJECT._serialized_start=448
  _PHYSICALOBJECT._serialized_end=572
  _PHYSICALOBJECTSLIST._serialized_start=574
  _PHYSICALOBJECTSLIST._serialized_end=647
# @@protoc_insertion_point(module_scope)
